Repository certtools/intelmq, pull requests merged in 2018-06, with the labels that each got.

#1241 DEP: lib/bot: replace parameter feed by name for collectors
  CHANGELOG.md
  NEWS.md
  intelmq/etc/runtime.conf
  intelmq/lib/bot.py
  intelmq/tests/bots/collectors/http/test_collector.py
  intelmq/tests/lib/test_collector_bot.py
Labels: component: core

#1243 Fix Shadowserver parser convert_http_host_and_url
  intelmq/bots/parsers/shadowserver/config.py
Labels: bug, component: bots

#1260 Minor typos and grammar
  docs/User-Guide.md
Labels: bug, documentation

#1197 Change classification in Shadowserver malware-related parsers
  NEWS.md
  intelmq/bots/parsers/shadowserver/config.py
  intelmq/tests/bots/parsers/shadowserver/test_drone_hadoop.py
  intelmq/tests/bots/parsers/shadowserver/test_microsoft_sinkhole.py
Labels: harmonization

#1166 Configurations Validator Tool (cerberus)
  intelmq/bin/configs-validators/README.md
  intelmq/bin/configs-validators/bots.schema.json
  intelmq/bin/configs-validators/feeds.schema.json
  intelmq/bin/configs-validators/intelmq-conf-validator
Labels: component: configuration, needs: feedback
