Repository certtools/intelmq, pull requests merged in 2020-10, with the labels that each got.

#1617 show bot name in feeds md
  docs/Feeds.md
  intelmq/bin/intelmq_gen_docs.py
Labels: documentation

#1607 Add key-value-parser bot
  docs/Bots.md
  intelmq/bots/BOTS
  intelmq/bots/parsers/key_value/__init__.py
  intelmq/bots/parsers/key_value/parser.py
  intelmq/tests/bots/parsers/key_value/__init__.py
  intelmq/tests/bots/parsers/key_value/test_parser.py
Labels: component: bots, feature request

#1599 ENH: CZ.NIC's Proki parser
  docs/Feeds.md
  intelmq/bots/BOTS
  intelmq/bots/parsers/cznic/parser_proki.py
  intelmq/etc/feeds.yaml
  intelmq/tests/bots/parsers/cznic/example_proki.json
  intelmq/tests/bots/parsers/cznic/test_parser_proki.py
Labels: component: bots, feature request

#1598 ENH: CERT-Bund feed for the Avalanche botnet
  docs/Feeds.md
  intelmq/etc/feeds.yaml
  intelmq/lib/bot.py
Labels: component: bots, documentation: feeds, feature request

#1606 BUG: fix cymru expert cache key calculation
  CHANGELOG.md
  NEWS.md
  intelmq/bots/experts/cymru_whois/expert.py
Labels: bug, component: bots

#1574 FIX: feed revision: DynDNS Infected Domains
  docs/Feeds.md
  intelmq/etc/feeds.yaml
Labels: component: bots, documentation: feeds

#1608 Add threshold expert bot
  docs/Bots.md
  intelmq/bots/BOTS
  intelmq/bots/experts/threshold/__init__.py
  intelmq/bots/experts/threshold/expert.py
  intelmq/tests/bots/experts/threshold/__init__.py
  intelmq/tests/bots/experts/threshold/test_expert.py
Labels: component: bots, feature request

#1620 sqlite docs updated
  CHANGELOG.md
  docs/Bots.md
  intelmq/lib/bot.py
Labels: documentation

#1624 Call upgrade-config and check at debian package upgrades
  debian/intelmq.postinst
Labels: packaging

#1627 Update URLs in README to the new canonical documentation URL
  README.rst
  setup.py
Labels: documentation

#1628 Check fallback paths of pipeline and runtime
  contrib/bash-completion/intelmqctl
  contrib/bash-completion/intelmqdump
Labels: bug, component: contrib

#1626 Do not show the powered by footer in the documentation
  docs/conf.py
Labels: documentation

#1623 parser_ctip: Update AZURE fields
  intelmq/bots/parsers/microsoft/parser_ctip.py
Labels: bug, component: bots

#1638 Refactor documentation
  .gitignore
  docs/_static/cef_logo.png
  docs/_static/intelmq-arch-schema.png
  docs/_static/intelmq-arch-schema.vsd
  docs/_static/intelmq_logo.jpg
  docs/_static/rabbitmq-user-monitoring.png
  docs/autogen.py
  docs/conf.py
  docs/dev/IntelMQ-3.0-Architecture.md
  docs/dev/data-harmonization.rst
  docs/dev/feeds-wishlist.rst
  docs/dev/guide.rst
  docs/dev/release-procedure.rst
  docs/guides/Data-Harmonization.md
  docs/guides/Ecosystem.md
  docs/guides/Feeds-whishlist.md
  docs/guides/INSTALL.md
  docs/guides/README.md
  docs/guides/Release.md
  docs/guides/UPGRADING.md
  docs/guides/images/Logo_Intel_MQ.svg
  docs/guides/intelmqctl.md
  docs/index.rst
  docs/user/ELK-Stack.rst
  docs/user/FAQ.rst
  docs/user/MISP-Integrations.rst
  docs/user/bots.rst
  docs/user/configuration-management.rst
  docs/user/ecosystem.rst
  docs/user/installation.rst
  docs/user/intelmqctl.rst
  docs/user/introduction.rst
  docs/user/n6-integrations.rst
  docs/user/upgrade.rst
Labels: documentation

#1642 Fix broke listing
  docs/user/configuration-management.rst
Labels: bug, documentation

#1641 Fix autogen to correctly display the 'public' status
  docs/autogen.py
Labels: bug, documentation

#1637 Rotating file handler added as another logging option
  intelmq/lib/bot.py
  intelmq/lib/utils.py
Labels: component: core, feature request
