Repository certtools/intelmq, pull requests merged in 2020-11, with the labels that each got.

#1643 Restructure the README and fix stale links
  README.rst
Labels: documentation

#1644 Use the extlinks sphinx extension to implement an `issue` command
  docs/conf.py
  docs/dev/feeds-wishlist.rst
  docs/user/FAQ.rst
  docs/user/bots.rst
  docs/user/configuration-management.rst
Labels: documentation

#1650 Fix some minor bugs in the documentation
  docs/user/ELK-Stack.rst
  docs/user/configuration-management.rst
  docs/user/intelmqctl.rst
Labels: bug, documentation

#1647 DOC 3.0 requirements: add evaluation, milestones
  docs/architecture-3.0.md
Labels: documentation

#1654 Implement a simple Kafka Collector
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/bots/BOTS
  intelmq/bots/collectors/kafka/REQUIREMENTS.txt
  intelmq/bots/collectors/kafka/collector.py
Labels: component: bots, feature request

#1660 fix bug in debugger
  intelmq/lib/bot_debugger.py
Labels: bug, component: intelmqctl

#1662 Drop the return statement, so the calling method gets to see the output
  intelmq/lib/bot_debugger.py
Labels: component: core, component: intelmqctl

#1664 Go over the configuration and management chapter
  docs/user/configuration-management.rst
Labels: documentation
