Repository certtools/intelmq, pull requests merged in 2021-06, with the labels that each got.

#1981 DOC: azure collector: document minimum azure version
  docs/user/bots.rst
  intelmq/bots/collectors/microsoft/collector_azure.py
Labels: component: bots, documentation

#1975 Compare "output" fields as JSON objects, not strings
  intelmq/lib/test.py
Labels: bug, component: tests

#1977 DOC: rt collector: document search_requestor parameter
  docs/user/bots.rst
  intelmq/bots/collectors/rt/collector_rt.py
Labels: bug, documentation

#1980 ENH: replace copy2 with pathlib
  intelmq/lib/utils.py
Labels: component: core

#1982 ENH: lib/bot: Init pipeline before init call
  CHANGELOG.md
  intelmq/lib/bot.py
  intelmq/lib/pipeline.py
  intelmq/lib/test.py
Labels: component: core

#1992 harm: move dga domain classification to other
  CHANGELOG.md
  NEWS.md
  docs/dev/data-format.rst
  intelmq/bots/experts/idea/expert.py
  intelmq/bots/experts/taxonomy/expert.py
  intelmq/bots/parsers/bambenek/parser.py
  intelmq/lib/harmonization.py
  intelmq/tests/bots/parsers/bambenek/test_parser.py
  intelmq/tests/lib/test_harmonization.py
Labels: component: core, harmonization

#1983 FIX: Use the default loader of ruamel yaml
  intelmq/lib/pipeline.py
  intelmq/lib/utils.py
Labels: component: core

#1993 harm: rename compromised to system-compromise
  CHANGELOG.md
  NEWS.md
  docs/dev/data-format.rst
  intelmq/bots/experts/idea/expert.py
  intelmq/bots/experts/taxonomy/expert.py
  intelmq/bots/parsers/cert_eu/parser_csv.py
  intelmq/bots/parsers/cymru/parser_cap_program.py
  intelmq/bots/parsers/cznic/parser_haas.py
  intelmq/bots/parsers/dyn/parser.py
  intelmq/bots/parsers/misp/parser.py
  intelmq/bots/parsers/shadowserver/_config.py
  intelmq/bots/parsers/spamhaus/parser_cert.py
  intelmq/bots/parsers/zoneh/parser.py
  intelmq/lib/harmonization.py
  intelmq/tests/bots/parsers/cznic/test_parser_haas.py
  intelmq/tests/bots/parsers/dyn/test_parser.py
  intelmq/tests/bots/parsers/shadowserver/test_compromised_website.py
  intelmq/tests/bots/parsers/shadowserver/test_scan_exchange.py
  intelmq/tests/bots/parsers/zoneh/test_zoneh.py
  intelmq/tests/lib/test_harmonization.py
Labels: component: core, harmonization

#1994 harm: remove type defacement
  CHANGELOG.md
  NEWS.md
  docs/dev/data-format.rst
  intelmq/bots/experts/idea/expert.py
  intelmq/bots/experts/taxonomy/expert.py
  intelmq/bots/parsers/cert_eu/parser_csv.py
  intelmq/bots/parsers/cymru/parser_cap_program.py
  intelmq/bots/parsers/misp/parser.py
  intelmq/bots/parsers/zoneh/parser.py
  intelmq/lib/harmonization.py
  intelmq/tests/bots/experts/field_reducer/test_expert.py
  intelmq/tests/bots/experts/filter/test_expert_absolute_after.py
  intelmq/tests/bots/experts/filter/test_expert_absolute_before.py
  intelmq/tests/bots/experts/filter/test_expert_regex_search.py
  intelmq/tests/bots/experts/filter/test_expert_relative_after.py
  intelmq/tests/bots/experts/filter/test_expert_relative_before.py
  intelmq/tests/bots/experts/filter/test_extra.py
  intelmq/tests/bots/experts/filter/test_paths.py
  intelmq/tests/bots/experts/taxonomy/test_expert.py
  intelmq/tests/bots/parsers/zoneh/test_zoneh.py
  intelmq/tests/lib/test_harmonization.py
Labels: component: core, harmonization

#1990 DOCS: Added timescaleDB extension
  CHANGELOG.md
  docs/user/eventdb.rst
Labels: documentation

#1979 DOCS: Updated release procedure for docker images
  docs/dev/release-procedure.rst
Labels: docker, documentation

#1987 API collector: Optionally use UNIX sockets instead of TCP sockets, fix #1986
  intelmq/bots/collectors/api/collector_api.py
Labels: bug, component: bots, feature request

#2000 BUG: lib/bot: ParserBot: mark internal variables correctly
  intelmq/bots/parsers/zoneh/parser.py
  intelmq/lib/bot.py
Labels: bug, component: core

#1998 Feeds documentation: Add benkow panels tracker
  intelmq/etc/feeds.yaml
Labels: documentation: feeds

#2006 harmonization: remove type dropzone
  CHANGELOG.md
  NEWS.md
  docs/dev/data-format.rst
  intelmq/bots/experts/idea/expert.py
  intelmq/bots/experts/taxonomy/expert.py
  intelmq/bots/parsers/cert_eu/parser_csv.py
  intelmq/bots/parsers/misp/parser.py
  intelmq/lib/harmonization.py
Labels: component: core, harmonization

#2010 BUG: utils/load_configuration: fix loading JSON with tabs
  intelmq/lib/utils.py
  intelmq/tests/assets/example-invalid.yaml
  intelmq/tests/assets/example-invalid.yaml.license
  intelmq/tests/assets/example.yaml
  intelmq/tests/assets/example.yaml.license
  intelmq/tests/assets/foobar.json
  intelmq/tests/assets/foobar.json.license
  intelmq/tests/assets/tab-whitespace.json
  intelmq/tests/assets/tab-whitespace.json.license
  intelmq/tests/lib/test_utils.py
Labels: bug, component: core

#2007 DOC: API: Add section on usage from programs
  docs/user/intelmq-api.rst
Labels: documentation
