Repository certtools/intelmq, pull requests merged in 2021-03, with the labels that each got.

#1766 FIX: Adds somewhat dirty fix for #1765.
  intelmq/lib/bot.py
  intelmq/lib/exceptions.py
  intelmq/lib/message.py
  intelmq/tests/lib/test_bot.py
Labels: bug, component: core

#1771 MAINT: Remove Malware Domain List feed
  docs/dev/guide.rst
  intelmq/bots/BOTS
  intelmq/bots/parsers/malwaredomainlist/__init__.py
  intelmq/bots/parsers/malwaredomainlist/parser.py
  intelmq/etc/feeds.yaml
  intelmq/etc/pipeline.conf
  intelmq/etc/runtime.conf
  intelmq/lib/upgrades.py
  intelmq/tests/bots/parsers/malwaredomainlist/__init__.py
  intelmq/tests/bots/parsers/malwaredomainlist/test_parser.py
  intelmq/tests/lib/test_upgrades.py
Labels: bug

#1769 Some Shadowserver API Collector and Parser fixes
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/bots/BOTS
  intelmq/bots/collectors/shadowserver/collector_reports_api.py
  intelmq/bots/parsers/shadowserver/config.py
  intelmq/bots/parsers/shadowserver/parser_json.py
  intelmq/tests/bots/collectors/shadowserver/test_collector_reports_api.py
  intelmq/tests/bots/parsers/shadowserver/test_botnet_drone.py
  intelmq/tests/bots/parsers/shadowserver/test_scan_smb_json.py
  intelmq/tests/bots/parsers/shadowserver/test_testdata.py
  intelmq/tests/bots/parsers/shadowserver/testdata/botnet_drone.csv
Labels: bug, component: bots

#1781 FIX: the pipeline factory expects a dict, not simply a list
  intelmq/lib/bot.py
  intelmq/lib/pipeline.py
Labels: bug, component: core

#1786 BUG: lib.utils.log: handle null logging_max_size
  CHANGELOG.md
  intelmq/lib/utils.py
Labels: bug, component: core

#1797 BUG: lib/bot and lib/test: fix pipeline parameter check
  intelmq/lib/bot.py
  intelmq/lib/test.py
Labels: bug, component: core, component: tests

#1788 DOC: add information about session permissions
  docs/user/intelmq-api.rst
Labels: documentation

#1798 DOC: add information about session permissions
  docs/user/intelmq-api.rst
Labels: documentation

#1795 Cymru CAP Parser: Adapt to new format of 'bruteforce' category
  CHANGELOG.md
  intelmq/bots/parsers/cymru/parser_cap_program.py
  intelmq/tests/bots/parsers/cymru/certname_20190327.txt
  intelmq/tests/bots/parsers/cymru/test_cap_program_new.py
Labels: bug, component: bots

#1787 extend intelmqsetup to api
  CHANGELOG.md
  intelmq/bin/intelmqctl.py
  intelmq/bin/intelmqsetup.py
Labels: component: core, usability

#1780 Update documentation regarding BOTS file and parameter handling
  docs/dev/guide.rst
  docs/user/bots.rst
  docs/user/configuration-management.rst
Labels: documentation

#1789 ENH: add http status code expert
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/bots/BOTS
  intelmq/bots/experts/http/__init__.py
  intelmq/bots/experts/http/expert_status.py
  intelmq/tests/bots/experts/http/test_expert_status.py
Labels: component: bots, feature request

#1809 docs: faq redis socket: less permissions
  CHANGELOG.md
  docs/user/FAQ.rst
Labels: documentation

#1806 DOC: Enhance API and Manager documentation
  docs/user/intelmq-api.rst
  docs/user/intelmq-manager.rst
Labels: documentation

#1805 intelmqsetup: fix api directories, setup webserver
  CHANGELOG.md
  debian/rules
  intelmq/bin/intelmqsetup.py
Labels: component: core, usability

#1801 DOC: bots: link ELK-Stack in bots/ES output
  docs/user/bots.rst
Labels: documentation

#1821 ENH: Improvements to the Shodan parser
  .gitignore
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/etc/feeds.yaml
Labels: component: bots, feature request

#1830 BUG: lib/pipeline: Ampq._get_qeues: ignore wrong vhost
  CHANGELOG.md
  intelmq/lib/pipeline.py
Labels: bug, component: core

#1831 Update _lib.py
  intelmq/bots/collectors/mail/_lib.py
Labels: component: bots, feature request

#1825 BUG TST: test_datetime_convert: skip if not UTC
  CHANGELOG.md
  intelmq/tests/lib/test_harmonization.py
Labels: component: tests

#1826 shadowserver collector: more debug logging
  CHANGELOG.md
  intelmq/bots/collectors/shadowserver/collector_reports_api.py
  intelmq/tests/bots/collectors/shadowserver/test_collector_reports_api.py
Labels: component: bots
