Repository certtools/intelmq, pull requests merged in 2021-01, with the labels that each got.

#1673 A couple of bug fixes and updates of the Debian package
  debian/changelog
  debian/control
  debian/py3dist-overrides
  debian/rules
Labels: packaging

#1696 [ENH] Sieve datetime operations
  docs/user/bots.rst
  intelmq/bots/experts/sieve/expert.py
  intelmq/bots/experts/sieve/sieve.tx
  intelmq/tests/bots/experts/sieve/test_expert.py
  intelmq/tests/bots/experts/sieve/test_sieve_files/test_basic_math.sieve
Labels: component: bots, feature request

#1701 PKG: Build the sphinx documentation during Debian package creation
  debian/rules
Labels: documentation, packaging

#1702 PKG: drop the dh-systemd dependency from the package
  debian/control
Labels: packaging

#1703 MAINT: Add a workflow that builds Debian packages
  .github/workflows/debian-package.yml
  .github/workflows/scripts/debian-package.sh
  .travis.yml
  debian/control
Labels: component: tests, packaging

#1700 Add Shadowserver API collector and JSON parser
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/bots/collectors/shadowserverapi/collector.py
  intelmq/bots/parsers/shadowserver/jsonparser.py
  intelmq/tests/bots/collectors/shadowserverapi/reports-list.json
  intelmq/tests/bots/collectors/shadowserverapi/test_collector.py
  intelmq/tests/bots/parsers/shadowserver/test_testdata.py
Labels: component: bots, feature request

#1667 Docker documentation
  docs/user/ecosystem.rst
  docs/user/installation.rst
  docs/user/upgrade.rst
Labels: docker, documentation

#1707 MAINT: Replace remainig Travis CI jobs with GitHub workflows
  .github/workflows/build-docs.yml
  .github/workflows/nosetests.yml
  .github/workflows/scripts/setup-full.sh
  .travis.yml
  CHANGELOG.md
  README.rst
  docs/dev/guide.rst
  docs/index.rst
  intelmq/lib/test.py
  intelmq/tests/bots/experts/abusix/test_expert.py
  intelmq/tests/bots/experts/cymru_whois/test_expert.py
  intelmq/tests/bots/experts/do_portal/test_expert.py
  intelmq/tests/bots/experts/national_cert_contact_certat/test_expert.py
  intelmq/tests/lib/test_pipeline.py
  setup.py
Labels: component: tests

#1713 DOC: Integrate documentation for intelmq-api
  docs/index.rst
  docs/user/intelmq-api.rst
Labels: documentation

#1714 DOC: integrate documentation for intelmq-manager
  docs/_static/intelmq-manager/configuration-path-form.png
  docs/_static/intelmq-manager/configuration-path-form.png.license
  docs/_static/intelmq-manager/configuration-path-set.png
  docs/_static/intelmq-manager/configuration-path-set.png.license
  docs/_static/intelmq-manager/configuration.png
  docs/_static/intelmq-manager/configuration.png.license
  docs/_static/intelmq-manager/configuration2.png
  docs/_static/intelmq-manager/configuration2.png.license
  docs/_static/intelmq-manager/management.png
  docs/_static/intelmq-manager/management.png.license
  docs/_static/intelmq-manager/monitor.png
  docs/_static/intelmq-manager/monitor.png.license
  docs/_static/intelmq-manager/monitor2.png
  docs/_static/intelmq-manager/monitor2.png.license
  docs/index.rst
  docs/user/intelmq-manager.rst
Labels: documentation

#1722 DOC: update intelmq-api documentation
  intelmq/etc/harmonization.conf
Labels: documentation
