Repository certtools/intelmq, pull requests merged in 2022-07, with the labels that each got.

#2198 intelmqsetup: Fix #2197
  CHANGELOG.md
  intelmq/bin/intelmqsetup.py
Labels: bug, component: core

#2201 Fix reconnection in SQL Mixin
  intelmq/lib/mixins/sql.py
Labels: bug, component: bots

#2192 ParserBot: Fix line recovery and message dumping
  CHANGELOG.md
  intelmq/bots/parsers/abusech/parser_ip.py
  intelmq/bots/parsers/cymru/parser_full_bogons.py
  intelmq/bots/parsers/generic/parser_csv.py
  intelmq/bots/parsers/microsoft/parser_ctip.py
  intelmq/bots/parsers/shadowserver/parser.py
  intelmq/lib/bot.py
  intelmq/lib/pipeline.py
  intelmq/tests/lib/test_parser_bot.py
Labels: bug, component: core

#2193 bug: fix ctip parser handling JSON Payload content
  CHANGELOG.md
  intelmq/bots/parsers/microsoft/parser_ctip.py
  intelmq/etc/feeds.yaml
  intelmq/tests/bots/parsers/microsoft/ctip_azure.txt
  intelmq/tests/bots/parsers/microsoft/test_parser_ctip_azure.py
Labels: bug, component: bots

#2225 docs: workaround for sphinx-doc/sphinx#10701
  CHANGELOG.md
  docs/conf.py
Labels: bug, documentation

#2214 FIX: Remove AutoShun from IntelMQ as the feed is discontinued
  .github/workflows/codespell.excludelines
  CHANGELOG.md
  intelmq/bots/parsers/autoshun/__init__.py
  intelmq/bots/parsers/autoshun/parser.py
  intelmq/etc/feeds.yaml
  intelmq/lib/upgrades.py
  intelmq/tests/bots/parsers/autoshun/__init__.py
  intelmq/tests/bots/parsers/autoshun/shunlist.html
  intelmq/tests/bots/parsers/autoshun/test_parser.py
  intelmq/tests/lib/test_upgrades.py
Labels: bug

#2172 SQL: add MSSQL support and allow storing only a subset of event fields
  CHANGELOG.md
  docs/user/bots.rst
  intelmq/bots/outputs/sql/REQUIREMENTS.txt
  intelmq/bots/outputs/sql/output.py
  intelmq/lib/mixins/sql.py
Labels: feature request, component: bots

#2145 ENH: Added personal access token support to GitHub Collector
  CHANGELOG.md
  NEWS.md
  docs/user/bots.rst
  intelmq/bots/collectors/github_api/_collector_github_api.py
  intelmq/etc/feeds.yaml
  intelmq/tests/bots/collectors/github_api/test_collector.py
Labels: bug, component: bots

#2149 FIX: Use redis BLMOVE instead of BRPOPLPUSH (deprecated)
  CHANGELOG.md
  intelmq/lib/pipeline.py
Labels: component: core
