Repository certtools/intelmq, pull requests merged in 2023-11, with the labels that each got.

#2413 Discover bots based on the entry points
  .gitignore
  CHANGELOG.md
  contrib/example-extension-package/mybots/__init__.py
  contrib/example-extension-package/mybots/bots/__init__.py
  contrib/example-extension-package/mybots/bots/collectors/__init__.py
  contrib/example-extension-package/mybots/bots/collectors/custom/__init__.py
  contrib/example-extension-package/mybots/bots/collectors/custom/collector.py
  contrib/example-extension-package/mybots/lib/__init__.py
  contrib/example-extension-package/mybots/lib/common.py
  contrib/example-extension-package/setup.py
  debian/control
  docs/dev/extensions-packages.md
  intelmq/bin/intelmqctl.py
  intelmq/lib/bot_debugger.py
  intelmq/lib/utils.py
  intelmq/tests/bin/test_intelmqctl.py
  intelmq/tests/lib/test_utils.py
  mkdocs.yml
  setup.py
Labels: feature request, component: core

#2426 DOC: Remove unused custom_template config
  mkdocs.yml
Labels: documentation

#2417 bots/collectors/api: make socket file permissions configurable
  CHANGELOG.md
  docs/user/bots.md
  intelmq/bots/collectors/api/collector_api.py
Labels: feature request, component: bots

#2427 doc: fix logo display in root repository
  docs/index.md
Labels: bug, documentation

#2432 ENH: upgrade: replace url2fqn by url expert
  CHANGELOG.md
  intelmq/etc/runtime.yaml
  intelmq/lib/upgrades.py
  intelmq/tests/lib/test_upgrades.py
Labels: bug, component: core, component: configuration
