Repository certtools/intelmq, pull requests merged in 2025-07, with the labels that each got.

#2621 ENH: add tor mapping and ipv6-icmp protocol to cymru parser
  CHANGELOG.md
  intelmq/bots/parsers/cymru/parser_cap_program.py
  intelmq/tests/bots/parsers/cymru/certname_20190327.txt
  intelmq/tests/bots/parsers/cymru/test_cap_program_new.py
Labels: component: bots

#2606 asn, fake expert: default paths, asn: add checks
  CHANGELOG.md
  intelmq/bots/experts/asn_lookup/expert.py
  intelmq/bots/experts/fake/expert.py
Labels: bug

#2601 fake: add new mode random_single_value
  CHANGELOG.md
  docs/user/bots.md
  intelmq/bots/experts/fake/expert.py
  intelmq/tests/bots/experts/fake/severity.json
  intelmq/tests/bots/experts/fake/severity.json.license
  intelmq/tests/bots/experts/fake/test_expert.py
Labels: component: bots

#2604 splitreports: handle empty string chunk_size
  CHANGELOG.md
  intelmq/lib/splitreports.py
Labels: bug

#2614 pkg: package complete contrib dir in new separate package
  CHANGELOG.md
  debian/control
  debian/intelmq-contrib.install
  debian/rules
Labels: packaging

#2605 Test for textX dependency in self-check
  CHANGELOG.md
  intelmq/bots/experts/sieve/expert.py
Labels: bug, component: bots

#2603 ctl run: fix overwriting logging level
  CHANGELOG.md
  intelmq/lib/bot_debugger.py
Labels: bug, component: intelmqctl

#2579 lib/test: show warnings and errors in case of mismatch
  CHANGELOG.md
  Makefile
  intelmq/lib/test.py
Labels: component: tests

#2627 fix asn database age check
  intelmq/bots/experts/asn_lookup/expert.py
Labels: bug, component: bots
