Repository certtools/intelmq, pull requests merged in 2025-08, with the labels that each got.

#2633 ti database expert: adapt URL
  CHANGELOG.md
  intelmq/bots/experts/trusted_introducer_lookup/expert.py
  intelmq/tests/bots/experts/trusted_introducer_lookup/test_expert.py
Labels: bug

#2628 debian packages: add python3-intelmq to control
  debian/changelog
  debian/control
Labels: packaging

#2630 Update docs on testing pre-releases
  docs/dev/bot-development.md
Labels: documentation

#2607 ctl: fix logging level filtering
  CHANGELOG.md
  intelmq/bin/intelmqctl.py
  intelmq/tests/assets/test-bot.log
  intelmq/tests/assets/test-bot.log.license
  intelmq/tests/bin/test_intelmqctl.py
Labels: bug, component: intelmqctl

#2574 Implement IEP009 - product & vuln. identification
  CHANGELOG.md
  NEWS.md
  intelmq/etc/harmonization.conf
  intelmq/lib/upgrades.py
  intelmq/tests/bin/initdb.sql
  intelmq/tests/lib/test_upgrades.py
Labels: feature, data-format
