Repository certtools/intelmq, pull requests merged in 2025-03, with the labels that each got.

#2533 Fix maintaining pipeline when using AMQP
  CHANGELOG.md
  intelmq/lib/pipeline.py
Labels: bug, component: core

#2577 cleanmx, MISP: replace deprecated utcfromtimestamp
  CHANGELOG.md
  intelmq/bots/parsers/cleanmx/parser.py
  intelmq/bots/parsers/misp/parser.py
Labels: bug, component: bots

#2572 Update pycodestyle
  .github/workflows/pycodestyle.yml
Labels: component: tests

#2580 REL: 3.4.0 Release
  CHANGELOG.md
  NEWS.md
  debian/changelog
  docs/admin/installation/linux-packages.md
  intelmq/lib/upgrades.py
  intelmq/tests/lib/test_upgrades.py
  intelmq/version.py
Labels: packaging

#2587 pkg: replace hardcoded /opt/intelmq/ paths with variables
  CHANGELOG.md
  debian/control
  debian/sedfile
  intelmq/bots/experts/domain_valid/expert.py
  intelmq/bots/experts/maxmind_geoip/expert.py
  intelmq/bots/experts/modify/expert.py
  intelmq/bots/experts/recordedfuture_iprisk/expert.py
  intelmq/bots/experts/sieve/expert.py
  intelmq/bots/experts/tor_nodes/expert.py
  intelmq/bots/outputs/bro_file/output.py
  intelmq/bots/outputs/file/output.py
  intelmq/bots/outputs/files/output.py
  intelmq/bots/outputs/misp/output_feed.py
  intelmq/bots/outputs/rpz_file/output.py
Labels: packaging
